### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by thefrana** [justrhysism/prettier-plugin-nunjucks#13]

**Comment by justrhysism** [comment]
It's experimental and not released. 

I did have some good cadence for a while but recently had a baby which has taken up the small amount of time I had left.

Professionally I'm not currently working with Nunjucks and won't be for the foreseeable future, so my professional needs for this plugin aren't there currently. Not to say I don't want to do it, but it has taken back seat in terms of priority.

Contributions are absolutely welcome.
